version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-stretch
    steps:
      - checkout
      - run: npm install
      - run: gulp
  test:
    docker:
      - image: circleci/node:8-stretch
    steps:
      - checkout
      - run: npm install
      - run: gulp test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test